<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

namespace Base;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *
 * ListReq 通用列表参数
 *
 * Generated from protobuf message <code>base.ListReq</code>
 */
class ListReq extends \Google\Protobuf\Internal\Message
{
    /**
     * 条件
     *
     * Generated from protobuf field <code>string cond = 1;</code>
     */
    protected $cond = '';
    /**
     * 页码
     *
     * Generated from protobuf field <code>int64 page = 2;</code>
     */
    protected $page = 0;
    /**
     * 页数
     *
     * Generated from protobuf field <code>int64 limit = 3;</code>
     */
    protected $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cond
     *           条件
     *     @type int|string $page
     *           页码
     *     @type int|string $limit
     *           页数
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * 条件
     *
     * Generated from protobuf field <code>string cond = 1;</code>
     * @return string
     */
    public function getCond()
    {
        return $this->cond;
    }

    /**
     * 条件
     *
     * Generated from protobuf field <code>string cond = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCond($var)
    {
        GPBUtil::checkString($var, True);
        $this->cond = $var;

        return $this;
    }

    /**
     * 页码
     *
     * Generated from protobuf field <code>int64 page = 2;</code>
     * @return int|string
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * 页码
     *
     * Generated from protobuf field <code>int64 page = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->page = $var;

        return $this;
    }

    /**
     * 页数
     *
     * Generated from protobuf field <code>int64 limit = 3;</code>
     * @return int|string
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * 页数
     *
     * Generated from protobuf field <code>int64 limit = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->limit = $var;

        return $this;
    }

}

