<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

namespace Base;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *
 * Map 通用
 *
 * Generated from protobuf message <code>base.Map</code>
 */
class Map extends \Google\Protobuf\Internal\Message
{
    /**
     *数据
     *
     * Generated from protobuf field <code>map<string, string> data = 1;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $data
     *          数据
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Base::initOnce();
        parent::__construct($data);
    }

    /**
     *数据
     *
     * Generated from protobuf field <code>map<string, string> data = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *数据
     *
     * Generated from protobuf field <code>map<string, string> data = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->data = $arr;

        return $this;
    }

}

