<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

namespace Base;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *
 * 空返回
 *
 * Generated from protobuf message <code>base.Empty</code>
 */
class PBEmpty extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Base::initOnce();
        parent::__construct($data);
    }

}

