<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pay.proto

namespace Pay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *
 * 生成支付单
 *
 * Generated from protobuf message <code>pay.OrderGenReq</code>
 */
class OrderGenReq extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户ID
     *
     * Generated from protobuf field <code>string uid = 1;</code>
     */
    protected $uid = '';
    /**
     * 订单编号
     *
     * Generated from protobuf field <code>string order_no = 2;</code>
     */
    protected $order_no = '';
    /**
     * 订单标题
     *
     * Generated from protobuf field <code>string title = 3;</code>
     */
    protected $title = '';
    /**
     * 支付价格
     *
     * Generated from protobuf field <code>uint64 price = 4;</code>
     */
    protected $price = 0;
    /**
     * 通知链接
     *
     * Generated from protobuf field <code>string notify_url = 5;</code>
     */
    protected $notify_url = '';
    /**
     * 订单备注
     *
     * Generated from protobuf field <code>string remarks = 6;</code>
     */
    protected $remarks = '';
    /**
     * 时间戳 秒
     *
     * Generated from protobuf field <code>uint64 timestamp = 7;</code>
     */
    protected $timestamp = 0;
    /**
     * 签名
     *
     * Generated from protobuf field <code>string sign = 8;</code>
     */
    protected $sign = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uid
     *           用户ID
     *     @type string $order_no
     *           订单编号
     *     @type string $title
     *           订单标题
     *     @type int|string $price
     *           支付价格
     *     @type string $notify_url
     *           通知链接
     *     @type string $remarks
     *           订单备注
     *     @type int|string $timestamp
     *           时间戳 秒
     *     @type string $sign
     *           签名
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pay::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>string uid = 1;</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>string uid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid = $var;

        return $this;
    }

    /**
     * 订单编号
     *
     * Generated from protobuf field <code>string order_no = 2;</code>
     * @return string
     */
    public function getOrderNo()
    {
        return $this->order_no;
    }

    /**
     * 订单编号
     *
     * Generated from protobuf field <code>string order_no = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_no = $var;

        return $this;
    }

    /**
     * 订单标题
     *
     * Generated from protobuf field <code>string title = 3;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * 订单标题
     *
     * Generated from protobuf field <code>string title = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * 支付价格
     *
     * Generated from protobuf field <code>uint64 price = 4;</code>
     * @return int|string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * 支付价格
     *
     * Generated from protobuf field <code>uint64 price = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkUint64($var);
        $this->price = $var;

        return $this;
    }

    /**
     * 通知链接
     *
     * Generated from protobuf field <code>string notify_url = 5;</code>
     * @return string
     */
    public function getNotifyUrl()
    {
        return $this->notify_url;
    }

    /**
     * 通知链接
     *
     * Generated from protobuf field <code>string notify_url = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNotifyUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->notify_url = $var;

        return $this;
    }

    /**
     * 订单备注
     *
     * Generated from protobuf field <code>string remarks = 6;</code>
     * @return string
     */
    public function getRemarks()
    {
        return $this->remarks;
    }

    /**
     * 订单备注
     *
     * Generated from protobuf field <code>string remarks = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->remarks = $var;

        return $this;
    }

    /**
     * 时间戳 秒
     *
     * Generated from protobuf field <code>uint64 timestamp = 7;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * 时间戳 秒
     *
     * Generated from protobuf field <code>uint64 timestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * 签名
     *
     * Generated from protobuf field <code>string sign = 8;</code>
     * @return string
     */
    public function getSign()
    {
        return $this->sign;
    }

    /**
     * 签名
     *
     * Generated from protobuf field <code>string sign = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSign($var)
    {
        GPBUtil::checkString($var, True);
        $this->sign = $var;

        return $this;
    }

}

