<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pay.proto

namespace Pay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *
 * 支付信息
 *
 * Generated from protobuf message <code>pay.PaymentInfoReq</code>
 */
class PaymentInfoReq extends \Google\Protobuf\Internal\Message
{
    /**
     * 支付单号
     *
     * Generated from protobuf field <code>string payment_no = 1;</code>
     */
    protected $payment_no = '';
    /**
     * 支付方式
     *
     * Generated from protobuf field <code>string pay_type = 2;</code>
     */
    protected $pay_type = '';
    /**
     * 支付密码
     *
     * Generated from protobuf field <code>string pay_password = 3;</code>
     */
    protected $pay_password = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $payment_no
     *           支付单号
     *     @type string $pay_type
     *           支付方式
     *     @type string $pay_password
     *           支付密码
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pay::initOnce();
        parent::__construct($data);
    }

    /**
     * 支付单号
     *
     * Generated from protobuf field <code>string payment_no = 1;</code>
     * @return string
     */
    public function getPaymentNo()
    {
        return $this->payment_no;
    }

    /**
     * 支付单号
     *
     * Generated from protobuf field <code>string payment_no = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_no = $var;

        return $this;
    }

    /**
     * 支付方式
     *
     * Generated from protobuf field <code>string pay_type = 2;</code>
     * @return string
     */
    public function getPayType()
    {
        return $this->pay_type;
    }

    /**
     * 支付方式
     *
     * Generated from protobuf field <code>string pay_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPayType($var)
    {
        GPBUtil::checkString($var, True);
        $this->pay_type = $var;

        return $this;
    }

    /**
     * 支付密码
     *
     * Generated from protobuf field <code>string pay_password = 3;</code>
     * @return string
     */
    public function getPayPassword()
    {
        return $this->pay_password;
    }

    /**
     * 支付密码
     *
     * Generated from protobuf field <code>string pay_password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPayPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->pay_password = $var;

        return $this;
    }

}

