<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pay.proto

namespace Pay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *
 * 支付方式
 *
 * Generated from protobuf message <code>pay.payType</code>
 */
class payType extends \Google\Protobuf\Internal\Message
{
    /**
     * 数据ID
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * 名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * 标识
     *
     * Generated from protobuf field <code>string tag = 3;</code>
     */
    protected $tag = '';
    /**
     * 图标
     *
     * Generated from protobuf field <code>string icon = 4;</code>
     */
    protected $icon = '';
    /**
     * 排序
     *
     * Generated from protobuf field <code>uint64 sort = 5;</code>
     */
    protected $sort = 0;
    /**
     * 备注
     *
     * Generated from protobuf field <code>string remarks = 6;</code>
     */
    protected $remarks = '';
    /**
     * 状态
     *
     * Generated from protobuf field <code>uint64 status = 7;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           数据ID
     *     @type string $name
     *           名称
     *     @type string $tag
     *           标识
     *     @type string $icon
     *           图标
     *     @type int|string $sort
     *           排序
     *     @type string $remarks
     *           备注
     *     @type int|string $status
     *           状态
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pay::initOnce();
        parent::__construct($data);
    }

    /**
     * 数据ID
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 数据ID
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * 名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * 标识
     *
     * Generated from protobuf field <code>string tag = 3;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * 标识
     *
     * Generated from protobuf field <code>string tag = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * 图标
     *
     * Generated from protobuf field <code>string icon = 4;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->icon;
    }

    /**
     * 图标
     *
     * Generated from protobuf field <code>string icon = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->icon = $var;

        return $this;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>uint64 sort = 5;</code>
     * @return int|string
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>uint64 sort = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkUint64($var);
        $this->sort = $var;

        return $this;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string remarks = 6;</code>
     * @return string
     */
    public function getRemarks()
    {
        return $this->remarks;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string remarks = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->remarks = $var;

        return $this;
    }

    /**
     * 状态
     *
     * Generated from protobuf field <code>uint64 status = 7;</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * 状态
     *
     * Generated from protobuf field <code>uint64 status = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint64($var);
        $this->status = $var;

        return $this;
    }

}

