<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pay.proto

namespace Pay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pay.RefundReq</code>
 */
class RefundReq extends \Google\Protobuf\Internal\Message
{
    /**
     * 支付单号
     *
     * Generated from protobuf field <code>string payment_no = 1;</code>
     */
    protected $payment_no = '';
    /**
     * 订单号
     *
     * Generated from protobuf field <code>string order_no = 2;</code>
     */
    protected $order_no = '';
    /**
     * 退款金额
     *
     * Generated from protobuf field <code>string refund_price = 3;</code>
     */
    protected $refund_price = '';
    /**
     * 备注
     *
     * Generated from protobuf field <code>string remarks = 4;</code>
     */
    protected $remarks = '';
    /**
     * 时间戳
     *
     * Generated from protobuf field <code>uint64 timestamp = 5;</code>
     */
    protected $timestamp = 0;
    /**
     * 签名
     *
     * Generated from protobuf field <code>uint64 sign = 6;</code>
     */
    protected $sign = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $payment_no
     *           支付单号
     *     @type string $order_no
     *           订单号
     *     @type string $refund_price
     *           退款金额
     *     @type string $remarks
     *           备注
     *     @type int|string $timestamp
     *           时间戳
     *     @type int|string $sign
     *           签名
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pay::initOnce();
        parent::__construct($data);
    }

    /**
     * 支付单号
     *
     * Generated from protobuf field <code>string payment_no = 1;</code>
     * @return string
     */
    public function getPaymentNo()
    {
        return $this->payment_no;
    }

    /**
     * 支付单号
     *
     * Generated from protobuf field <code>string payment_no = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_no = $var;

        return $this;
    }

    /**
     * 订单号
     *
     * Generated from protobuf field <code>string order_no = 2;</code>
     * @return string
     */
    public function getOrderNo()
    {
        return $this->order_no;
    }

    /**
     * 订单号
     *
     * Generated from protobuf field <code>string order_no = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_no = $var;

        return $this;
    }

    /**
     * 退款金额
     *
     * Generated from protobuf field <code>string refund_price = 3;</code>
     * @return string
     */
    public function getRefundPrice()
    {
        return $this->refund_price;
    }

    /**
     * 退款金额
     *
     * Generated from protobuf field <code>string refund_price = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRefundPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->refund_price = $var;

        return $this;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string remarks = 4;</code>
     * @return string
     */
    public function getRemarks()
    {
        return $this->remarks;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string remarks = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->remarks = $var;

        return $this;
    }

    /**
     * 时间戳
     *
     * Generated from protobuf field <code>uint64 timestamp = 5;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * 时间戳
     *
     * Generated from protobuf field <code>uint64 timestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * 签名
     *
     * Generated from protobuf field <code>uint64 sign = 6;</code>
     * @return int|string
     */
    public function getSign()
    {
        return $this->sign;
    }

    /**
     * 签名
     *
     * Generated from protobuf field <code>uint64 sign = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSign($var)
    {
        GPBUtil::checkUint64($var);
        $this->sign = $var;

        return $this;
    }

}

