<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *
 * Attr详情
 *
 * Generated from protobuf message <code>product.AttrItem</code>
 */
class AttrItem extends \Google\Protobuf\Internal\Message
{
    /**
     * 数据ID,创建时传0
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * 属性名
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * 属性描述
     *
     * Generated from protobuf field <code>string desc = 3;</code>
     */
    protected $desc = '';
    /**
     * AttrKey
     *
     * Generated from protobuf field <code>string key = 4;</code>
     */
    protected $key = '';
    /**
     * 是否重要属性 0否 1是
     *
     * Generated from protobuf field <code>bool is_important = 5;</code>
     */
    protected $is_important = false;
    /**
     * 是否必填 0否 1是
     *
     * Generated from protobuf field <code>bool is_required = 6;</code>
     */
    protected $is_required = false;
    /**
     * 是否自定义添加 0否 1是
     *
     * Generated from protobuf field <code>bool is_custom = 7;</code>
     */
    protected $is_custom = false;
    /**
     * form类型 input, select, checkbox
     *
     * Generated from protobuf field <code>string form_type = 8;</code>
     */
    protected $form_type = '';
    /**
     * form类型 input时，默认值，select, checkbox时,可选范围项
     *
     * Generated from protobuf field <code>string form_optional = 9;</code>
     */
    protected $form_optional = '';
    /**
     * 自定义标签
     *
     * Generated from protobuf field <code>string custom_label = 10;</code>
     */
    protected $custom_label = '';
    /**
     * 排序
     *
     * Generated from protobuf field <code>int64 sort = 11;</code>
     */
    protected $sort = 0;
    /**
     * 状态
     *
     * Generated from protobuf field <code>int64 status = 12;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           数据ID,创建时传0
     *     @type string $name
     *           属性名
     *     @type string $desc
     *           属性描述
     *     @type string $key
     *           AttrKey
     *     @type bool $is_important
     *           是否重要属性 0否 1是
     *     @type bool $is_required
     *           是否必填 0否 1是
     *     @type bool $is_custom
     *           是否自定义添加 0否 1是
     *     @type string $form_type
     *           form类型 input, select, checkbox
     *     @type string $form_optional
     *           form类型 input时，默认值，select, checkbox时,可选范围项
     *     @type string $custom_label
     *           自定义标签
     *     @type int|string $sort
     *           排序
     *     @type int|string $status
     *           状态
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * 数据ID,创建时传0
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 数据ID,创建时传0
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * 属性名
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 属性名
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * 属性描述
     *
     * Generated from protobuf field <code>string desc = 3;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * 属性描述
     *
     * Generated from protobuf field <code>string desc = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->desc = $var;

        return $this;
    }

    /**
     * AttrKey
     *
     * Generated from protobuf field <code>string key = 4;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * AttrKey
     *
     * Generated from protobuf field <code>string key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * 是否重要属性 0否 1是
     *
     * Generated from protobuf field <code>bool is_important = 5;</code>
     * @return bool
     */
    public function getIsImportant()
    {
        return $this->is_important;
    }

    /**
     * 是否重要属性 0否 1是
     *
     * Generated from protobuf field <code>bool is_important = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsImportant($var)
    {
        GPBUtil::checkBool($var);
        $this->is_important = $var;

        return $this;
    }

    /**
     * 是否必填 0否 1是
     *
     * Generated from protobuf field <code>bool is_required = 6;</code>
     * @return bool
     */
    public function getIsRequired()
    {
        return $this->is_required;
    }

    /**
     * 是否必填 0否 1是
     *
     * Generated from protobuf field <code>bool is_required = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->is_required = $var;

        return $this;
    }

    /**
     * 是否自定义添加 0否 1是
     *
     * Generated from protobuf field <code>bool is_custom = 7;</code>
     * @return bool
     */
    public function getIsCustom()
    {
        return $this->is_custom;
    }

    /**
     * 是否自定义添加 0否 1是
     *
     * Generated from protobuf field <code>bool is_custom = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCustom($var)
    {
        GPBUtil::checkBool($var);
        $this->is_custom = $var;

        return $this;
    }

    /**
     * form类型 input, select, checkbox
     *
     * Generated from protobuf field <code>string form_type = 8;</code>
     * @return string
     */
    public function getFormType()
    {
        return $this->form_type;
    }

    /**
     * form类型 input, select, checkbox
     *
     * Generated from protobuf field <code>string form_type = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFormType($var)
    {
        GPBUtil::checkString($var, True);
        $this->form_type = $var;

        return $this;
    }

    /**
     * form类型 input时，默认值，select, checkbox时,可选范围项
     *
     * Generated from protobuf field <code>string form_optional = 9;</code>
     * @return string
     */
    public function getFormOptional()
    {
        return $this->form_optional;
    }

    /**
     * form类型 input时，默认值，select, checkbox时,可选范围项
     *
     * Generated from protobuf field <code>string form_optional = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setFormOptional($var)
    {
        GPBUtil::checkString($var, True);
        $this->form_optional = $var;

        return $this;
    }

    /**
     * 自定义标签
     *
     * Generated from protobuf field <code>string custom_label = 10;</code>
     * @return string
     */
    public function getCustomLabel()
    {
        return $this->custom_label;
    }

    /**
     * 自定义标签
     *
     * Generated from protobuf field <code>string custom_label = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->custom_label = $var;

        return $this;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>int64 sort = 11;</code>
     * @return int|string
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>int64 sort = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkInt64($var);
        $this->sort = $var;

        return $this;
    }

    /**
     * 状态
     *
     * Generated from protobuf field <code>int64 status = 12;</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * 状态
     *
     * Generated from protobuf field <code>int64 status = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

}

