<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *
 * Category 详情
 *
 * Generated from protobuf message <code>product.CategoryItem</code>
 */
class CategoryItem extends \Google\Protobuf\Internal\Message
{
    /**
     * 数据ID,创建时传0
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * 父ID
     *
     * Generated from protobuf field <code>int64 pid = 2;</code>
     */
    protected $pid = 0;
    /**
     * 分类名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * 分类描述
     *
     * Generated from protobuf field <code>string desc = 4;</code>
     */
    protected $desc = '';
    /**
     * 分类图片
     *
     * Generated from protobuf field <code>string pic_url = 5;</code>
     */
    protected $pic_url = '';
    /**
     * 排序
     *
     * Generated from protobuf field <code>int64 sort = 6;</code>
     */
    protected $sort = 0;
    /**
     * 自定义标签
     *
     * Generated from protobuf field <code>string custom_label = 7;</code>
     */
    protected $custom_label = '';
    /**
     * 是否为叶子分类
     *
     * Generated from protobuf field <code>int64 is_leaf = 8;</code>
     */
    protected $is_leaf = 0;
    /**
     * 状态 1:enable, 0:disable
     *
     * Generated from protobuf field <code>int64 status = 9;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           数据ID,创建时传0
     *     @type int|string $pid
     *           父ID
     *     @type string $name
     *           分类名称
     *     @type string $desc
     *           分类描述
     *     @type string $pic_url
     *           分类图片
     *     @type int|string $sort
     *           排序
     *     @type string $custom_label
     *           自定义标签
     *     @type int|string $is_leaf
     *           是否为叶子分类
     *     @type int|string $status
     *           状态 1:enable, 0:disable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * 数据ID,创建时传0
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 数据ID,创建时传0
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * 父ID
     *
     * Generated from protobuf field <code>int64 pid = 2;</code>
     * @return int|string
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * 父ID
     *
     * Generated from protobuf field <code>int64 pid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkInt64($var);
        $this->pid = $var;

        return $this;
    }

    /**
     * 分类名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 分类名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * 分类描述
     *
     * Generated from protobuf field <code>string desc = 4;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * 分类描述
     *
     * Generated from protobuf field <code>string desc = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->desc = $var;

        return $this;
    }

    /**
     * 分类图片
     *
     * Generated from protobuf field <code>string pic_url = 5;</code>
     * @return string
     */
    public function getPicUrl()
    {
        return $this->pic_url;
    }

    /**
     * 分类图片
     *
     * Generated from protobuf field <code>string pic_url = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPicUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->pic_url = $var;

        return $this;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>int64 sort = 6;</code>
     * @return int|string
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>int64 sort = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkInt64($var);
        $this->sort = $var;

        return $this;
    }

    /**
     * 自定义标签
     *
     * Generated from protobuf field <code>string custom_label = 7;</code>
     * @return string
     */
    public function getCustomLabel()
    {
        return $this->custom_label;
    }

    /**
     * 自定义标签
     *
     * Generated from protobuf field <code>string custom_label = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->custom_label = $var;

        return $this;
    }

    /**
     * 是否为叶子分类
     *
     * Generated from protobuf field <code>int64 is_leaf = 8;</code>
     * @return int|string
     */
    public function getIsLeaf()
    {
        return $this->is_leaf;
    }

    /**
     * 是否为叶子分类
     *
     * Generated from protobuf field <code>int64 is_leaf = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIsLeaf($var)
    {
        GPBUtil::checkInt64($var);
        $this->is_leaf = $var;

        return $this;
    }

    /**
     * 状态 1:enable, 0:disable
     *
     * Generated from protobuf field <code>int64 status = 9;</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * 状态 1:enable, 0:disable
     *
     * Generated from protobuf field <code>int64 status = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

}

