<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>product.ProductAttr</code>
 */
class ProductAttr extends \Google\Protobuf\Internal\Message
{
    /**
     * 属性ID
     *
     * Generated from protobuf field <code>int64 attr_id = 1;</code>
     */
    protected $attr_id = 0;
    /**
     * 属性值
     *
     * Generated from protobuf field <code>string value = 2;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $attr_id
     *           属性ID
     *     @type string $value
     *           属性值
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * 属性ID
     *
     * Generated from protobuf field <code>int64 attr_id = 1;</code>
     * @return int|string
     */
    public function getAttrId()
    {
        return $this->attr_id;
    }

    /**
     * 属性ID
     *
     * Generated from protobuf field <code>int64 attr_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAttrId($var)
    {
        GPBUtil::checkInt64($var);
        $this->attr_id = $var;

        return $this;
    }

    /**
     * 属性值
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * 属性值
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

