<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *
 * Product 详情
 *
 * Generated from protobuf message <code>product.ProductItem</code>
 */
class ProductItem extends \Google\Protobuf\Internal\Message
{
    /**
     * 数据ID,创建时传0
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * 分类ID
     *
     * Generated from protobuf field <code>int64 category_id = 2;</code>
     */
    protected $category_id = 0;
    /**
     * 商品名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * 库存
     *
     * Generated from protobuf field <code>int64 in_stock = 4;</code>
     */
    protected $in_stock = 0;
    /**
     * 已售数量
     *
     * Generated from protobuf field <code>int64 sales = 5;</code>
     */
    protected $sales = 0;
    /**
     * 封面图
     *
     * Generated from protobuf field <code>string cover_url = 6;</code>
     */
    protected $cover_url = '';
    /**
     * 介绍视频
     *
     * Generated from protobuf field <code>string video_url = 7;</code>
     */
    protected $video_url = '';
    /**
     * 是否推荐
     *
     * Generated from protobuf field <code>bool is_recommend = 8;</code>
     */
    protected $is_recommend = false;
    /**
     * 售价，整数方式保存
     *
     * Generated from protobuf field <code>int64 price_fee = 9;</code>
     */
    protected $price_fee = 0;
    /**
     * 市场价，整数方式保存
     *
     * Generated from protobuf field <code>int64 market_price_fee = 10;</code>
     */
    protected $market_price_fee = 0;
    /**
     * 自定义标签
     *
     * Generated from protobuf field <code>int64 custom_label = 11;</code>
     */
    protected $custom_label = 0;
    /**
     * 详情类型 容类型:html json
     *
     * Generated from protobuf field <code>string content_type = 12;</code>
     */
    protected $content_type = '';
    /**
     * 详情
     *
     * Generated from protobuf field <code>string content = 13;</code>
     */
    protected $content = '';
    /**
     * 类目属性
     *
     * Generated from protobuf field <code>repeated .product.ProductAttr cate_attrs = 14;</code>
     */
    private $cate_attrs;
    /**
     * 销售属性
     *
     * Generated from protobuf field <code>repeated .product.ProductAttrGroup sale_group = 15;</code>
     */
    private $sale_group;
    /**
     * 销售规格
     *
     * Generated from protobuf field <code>repeated .product.ProductSku sku = 16;</code>
     */
    private $sku;
    /**
     * 排序
     *
     * Generated from protobuf field <code>int64 sort = 17;</code>
     */
    protected $sort = 0;
    /**
     * 状态 1:enable, 0:disable
     *
     * Generated from protobuf field <code>int64 status = 18;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           数据ID,创建时传0
     *     @type int|string $category_id
     *           分类ID
     *     @type string $name
     *           商品名称
     *     @type int|string $in_stock
     *           库存
     *     @type int|string $sales
     *           已售数量
     *     @type string $cover_url
     *           封面图
     *     @type string $video_url
     *           介绍视频
     *     @type bool $is_recommend
     *           是否推荐
     *     @type int|string $price_fee
     *           售价，整数方式保存
     *     @type int|string $market_price_fee
     *           市场价，整数方式保存
     *     @type int|string $custom_label
     *           自定义标签
     *     @type string $content_type
     *           详情类型 容类型:html json
     *     @type string $content
     *           详情
     *     @type array<\Product\ProductAttr>|\Google\Protobuf\Internal\RepeatedField $cate_attrs
     *           类目属性
     *     @type array<\Product\ProductAttrGroup>|\Google\Protobuf\Internal\RepeatedField $sale_group
     *           销售属性
     *     @type array<\Product\ProductSku>|\Google\Protobuf\Internal\RepeatedField $sku
     *           销售规格
     *     @type int|string $sort
     *           排序
     *     @type int|string $status
     *           状态 1:enable, 0:disable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * 数据ID,创建时传0
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 数据ID,创建时传0
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * 分类ID
     *
     * Generated from protobuf field <code>int64 category_id = 2;</code>
     * @return int|string
     */
    public function getCategoryId()
    {
        return $this->category_id;
    }

    /**
     * 分类ID
     *
     * Generated from protobuf field <code>int64 category_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkInt64($var);
        $this->category_id = $var;

        return $this;
    }

    /**
     * 商品名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 商品名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * 库存
     *
     * Generated from protobuf field <code>int64 in_stock = 4;</code>
     * @return int|string
     */
    public function getInStock()
    {
        return $this->in_stock;
    }

    /**
     * 库存
     *
     * Generated from protobuf field <code>int64 in_stock = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInStock($var)
    {
        GPBUtil::checkInt64($var);
        $this->in_stock = $var;

        return $this;
    }

    /**
     * 已售数量
     *
     * Generated from protobuf field <code>int64 sales = 5;</code>
     * @return int|string
     */
    public function getSales()
    {
        return $this->sales;
    }

    /**
     * 已售数量
     *
     * Generated from protobuf field <code>int64 sales = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSales($var)
    {
        GPBUtil::checkInt64($var);
        $this->sales = $var;

        return $this;
    }

    /**
     * 封面图
     *
     * Generated from protobuf field <code>string cover_url = 6;</code>
     * @return string
     */
    public function getCoverUrl()
    {
        return $this->cover_url;
    }

    /**
     * 封面图
     *
     * Generated from protobuf field <code>string cover_url = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCoverUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->cover_url = $var;

        return $this;
    }

    /**
     * 介绍视频
     *
     * Generated from protobuf field <code>string video_url = 7;</code>
     * @return string
     */
    public function getVideoUrl()
    {
        return $this->video_url;
    }

    /**
     * 介绍视频
     *
     * Generated from protobuf field <code>string video_url = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setVideoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->video_url = $var;

        return $this;
    }

    /**
     * 是否推荐
     *
     * Generated from protobuf field <code>bool is_recommend = 8;</code>
     * @return bool
     */
    public function getIsRecommend()
    {
        return $this->is_recommend;
    }

    /**
     * 是否推荐
     *
     * Generated from protobuf field <code>bool is_recommend = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRecommend($var)
    {
        GPBUtil::checkBool($var);
        $this->is_recommend = $var;

        return $this;
    }

    /**
     * 售价，整数方式保存
     *
     * Generated from protobuf field <code>int64 price_fee = 9;</code>
     * @return int|string
     */
    public function getPriceFee()
    {
        return $this->price_fee;
    }

    /**
     * 售价，整数方式保存
     *
     * Generated from protobuf field <code>int64 price_fee = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPriceFee($var)
    {
        GPBUtil::checkInt64($var);
        $this->price_fee = $var;

        return $this;
    }

    /**
     * 市场价，整数方式保存
     *
     * Generated from protobuf field <code>int64 market_price_fee = 10;</code>
     * @return int|string
     */
    public function getMarketPriceFee()
    {
        return $this->market_price_fee;
    }

    /**
     * 市场价，整数方式保存
     *
     * Generated from protobuf field <code>int64 market_price_fee = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMarketPriceFee($var)
    {
        GPBUtil::checkInt64($var);
        $this->market_price_fee = $var;

        return $this;
    }

    /**
     * 自定义标签
     *
     * Generated from protobuf field <code>int64 custom_label = 11;</code>
     * @return int|string
     */
    public function getCustomLabel()
    {
        return $this->custom_label;
    }

    /**
     * 自定义标签
     *
     * Generated from protobuf field <code>int64 custom_label = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCustomLabel($var)
    {
        GPBUtil::checkInt64($var);
        $this->custom_label = $var;

        return $this;
    }

    /**
     * 详情类型 容类型:html json
     *
     * Generated from protobuf field <code>string content_type = 12;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * 详情类型 容类型:html json
     *
     * Generated from protobuf field <code>string content_type = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->content_type = $var;

        return $this;
    }

    /**
     * 详情
     *
     * Generated from protobuf field <code>string content = 13;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * 详情
     *
     * Generated from protobuf field <code>string content = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * 类目属性
     *
     * Generated from protobuf field <code>repeated .product.ProductAttr cate_attrs = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCateAttrs()
    {
        return $this->cate_attrs;
    }

    /**
     * 类目属性
     *
     * Generated from protobuf field <code>repeated .product.ProductAttr cate_attrs = 14;</code>
     * @param array<\Product\ProductAttr>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCateAttrs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Product\ProductAttr::class);
        $this->cate_attrs = $arr;

        return $this;
    }

    /**
     * 销售属性
     *
     * Generated from protobuf field <code>repeated .product.ProductAttrGroup sale_group = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSaleGroup()
    {
        return $this->sale_group;
    }

    /**
     * 销售属性
     *
     * Generated from protobuf field <code>repeated .product.ProductAttrGroup sale_group = 15;</code>
     * @param array<\Product\ProductAttrGroup>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSaleGroup($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Product\ProductAttrGroup::class);
        $this->sale_group = $arr;

        return $this;
    }

    /**
     * 销售规格
     *
     * Generated from protobuf field <code>repeated .product.ProductSku sku = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * 销售规格
     *
     * Generated from protobuf field <code>repeated .product.ProductSku sku = 16;</code>
     * @param array<\Product\ProductSku>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSku($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Product\ProductSku::class);
        $this->sku = $arr;

        return $this;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>int64 sort = 17;</code>
     * @return int|string
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>int64 sort = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkInt64($var);
        $this->sort = $var;

        return $this;
    }

    /**
     * 状态 1:enable, 0:disable
     *
     * Generated from protobuf field <code>int64 status = 18;</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * 状态 1:enable, 0:disable
     *
     * Generated from protobuf field <code>int64 status = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

}

