<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>product.ProductAttrGroup</code>
 */
class ProductAttrGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * 分组ID
     *
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     */
    protected $group_id = 0;
    /**
     * 分组名称
     *
     * Generated from protobuf field <code>string group_name = 2;</code>
     */
    protected $group_name = '';
    /**
     * 销售属性
     *
     * Generated from protobuf field <code>repeated .product.ProductAttr attrs = 3;</code>
     */
    private $attrs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $group_id
     *           分组ID
     *     @type string $group_name
     *           分组名称
     *     @type array<\Product\ProductAttr>|\Google\Protobuf\Internal\RepeatedField $attrs
     *           销售属性
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * 分组ID
     *
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * 分组ID
     *
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * 分组名称
     *
     * Generated from protobuf field <code>string group_name = 2;</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->group_name;
    }

    /**
     * 分组名称
     *
     * Generated from protobuf field <code>string group_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_name = $var;

        return $this;
    }

    /**
     * 销售属性
     *
     * Generated from protobuf field <code>repeated .product.ProductAttr attrs = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttrs()
    {
        return $this->attrs;
    }

    /**
     * 销售属性
     *
     * Generated from protobuf field <code>repeated .product.ProductAttr attrs = 3;</code>
     * @param array<\Product\ProductAttr>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttrs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Product\ProductAttr::class);
        $this->attrs = $arr;

        return $this;
    }

}

