<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *
 * APP列表
 *
 * Generated from protobuf message <code>user.AppListResp</code>
 */
class AppListResp extends \Google\Protobuf\Internal\Message
{
    /**
     * 列表
     *
     * Generated from protobuf field <code>repeated .user.AppItem items = 1;</code>
     */
    private $items;
    /**
     * 总数
     *
     * Generated from protobuf field <code>int64 total = 2;</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\User\AppItem>|\Google\Protobuf\Internal\RepeatedField $items
     *           列表
     *     @type int|string $total
     *           总数
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 列表
     *
     * Generated from protobuf field <code>repeated .user.AppItem items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * 列表
     *
     * Generated from protobuf field <code>repeated .user.AppItem items = 1;</code>
     * @param array<\User\AppItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \User\AppItem::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * 总数
     *
     * Generated from protobuf field <code>int64 total = 2;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * 总数
     *
     * Generated from protobuf field <code>int64 total = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

}

